// Code Generated by Sidekick is for learning and experimentation purposes only.
package com.smartwatch.leaderboard.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.smartwatch.leaderboard.dto.request.ChallengeRequest;
import com.smartwatch.leaderboard.dto.response.ChallengeResponse;
import com.smartwatch.leaderboard.dto.response.UserChallengeRankResponse;
import com.smartwatch.leaderboard.dto.response.UserChallengeResponse;
import com.smartwatch.leaderboard.model.enums.ChallengeStatus;
import com.smartwatch.leaderboard.model.enums.UserChallengeStatus;
import com.smartwatch.leaderboard.service.ChallengeService;
import com.smartwatch.leaderboard.utils.JwtUtil;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;

import java.time.LocalDateTime;
import java.util.List;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest(ChallengeController.class)
@Import(ChallengeControllerTest.TestSecurityConfig.class)
@AutoConfigureMockMvc(addFilters = false)
class ChallengeControllerTest {

    @Autowired private MockMvc mockMvc;
    @Autowired private ObjectMapper objectMapper;

    @MockBean private ChallengeService challengeService;
    @MockBean private JwtUtil jwtUtil;

    @EnableMethodSecurity
    static class TestSecurityConfig { }

    private ChallengeRequest validRequest;
    private LocalDateTime startTime;
    private LocalDateTime endTime;

    @BeforeEach
    void setUp() {
        // Ensure ObjectMapper handles LocalDateTime
        objectMapper.registerModule(new JavaTimeModule());

        startTime = LocalDateTime.of(2026, 6, 1, 0, 0);
        endTime = LocalDateTime.of(2026, 6, 30, 23, 59);

        validRequest = new ChallengeRequest();
        validRequest.setName("10K Steps Challenge");
        validRequest.setDescription("Walk 10,000 steps daily");
        validRequest.setRequiredLevelId(1L);
        validRequest.setStartTime(startTime);
        validRequest.setEndTime(endTime);
        validRequest.setStatus("ACTIVE");
        validRequest.setRewardScheme("POINTS");
        validRequest.setTaskIds(List.of(101L, 102L));
    }

    private ChallengeResponse buildChallengeResponse(Long id, String name) {
        return ChallengeResponse.builder()
                .id(id)
                .name(name)
                .description("desc")
                .requiredLevelId(1L)
                .requiredLevelName("Beginner")
                .startTime(startTime)
                .endTime(endTime)
                .status(ChallengeStatus.ACTIVE)
                .rewardScheme("POINTS")
                .createdByUserId(99L)
                .tasks(List.of())
                .build();
    }

    // ========== POST /challenges ==========

    @Test
    @WithMockUser(username = "user@test.com", roles = "USER")
    void createChallenge_shouldReturn201ForUser() throws Exception {
        ChallengeResponse mockResponse = buildChallengeResponse(1L, "10K Steps Challenge");

        when(challengeService.createChallenge(any(ChallengeRequest.class), eq("user@test.com")))
                .thenReturn(mockResponse);

        mockMvc.perform(post("/challenges")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(validRequest)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.id").value(1))
                .andExpect(jsonPath("$.name").value("10K Steps Challenge"))
                .andExpect(jsonPath("$.status").value("ACTIVE"))
                .andExpect(jsonPath("$.rewardScheme").value("POINTS"));

        verify(challengeService).createChallenge(any(ChallengeRequest.class), eq("user@test.com"));
    }

    @Test
    @WithMockUser(username = "admin@test.com", roles = "ADMIN")
    void createChallenge_shouldReturn201ForAdmin() throws Exception {
        ChallengeResponse mockResponse = buildChallengeResponse(2L, "Admin Challenge");

        when(challengeService.createChallenge(any(ChallengeRequest.class), eq("admin@test.com")))
                .thenReturn(mockResponse);

        mockMvc.perform(post("/challenges")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(validRequest)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.id").value(2));
    }

    // ========== GET /challenges ==========

    @Test
    @WithMockUser(username = "user@test.com", roles = "USER")
    void getChallenges_shouldReturnListForUser() throws Exception {
        ChallengeResponse c1 = buildChallengeResponse(1L, "Challenge 1");
        ChallengeResponse c2 = buildChallengeResponse(2L, "Challenge 2");

        when(challengeService.getChallengesForUser("user@test.com"))
                .thenReturn(List.of(c1, c2));

        mockMvc.perform(get("/challenges"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(2))
                .andExpect(jsonPath("$[0].id").value(1))
                .andExpect(jsonPath("$[0].name").value("Challenge 1"))
                .andExpect(jsonPath("$[1].id").value(2));

        verify(challengeService).getChallengesForUser("user@test.com");
    }

    @Test
    @WithMockUser(username = "user@test.com", roles = "USER")
    void getChallenges_shouldReturnEmptyList() throws Exception {
        when(challengeService.getChallengesForUser("user@test.com"))
                .thenReturn(List.of());

        mockMvc.perform(get("/challenges"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(0));
    }

    // ========== GET /challenges/{id} ==========

    @Test
    @WithMockUser(roles = "USER")
    void getChallengeById_shouldReturn200() throws Exception {
        ChallengeResponse mockResponse = buildChallengeResponse(42L, "Found Challenge");

        when(challengeService.getChallengeById(42L)).thenReturn(mockResponse);

        mockMvc.perform(get("/challenges/42"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(42))
                .andExpect(jsonPath("$.name").value("Found Challenge"));

        verify(challengeService).getChallengeById(42L);
    }

    // ========== PUT /challenges/{id} — ADMIN ONLY ==========

    @Test
    @WithMockUser(roles = "ADMIN")
    void updateChallenge_shouldReturn200ForAdmin() throws Exception {
        ChallengeResponse mockResponse = buildChallengeResponse(7L, "Updated Challenge");

        when(challengeService.updateChallenge(eq(7L), any(ChallengeRequest.class)))
                .thenReturn(mockResponse);

        mockMvc.perform(put("/challenges/7")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(validRequest)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(7))
                .andExpect(jsonPath("$.name").value("Updated Challenge"));

        verify(challengeService).updateChallenge(eq(7L), any(ChallengeRequest.class));
    }

    @Test
    @WithMockUser(roles = "USER")
    void updateChallenge_shouldReturn403ForUser() throws Exception {
        mockMvc.perform(put("/challenges/7")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(validRequest)))
                .andExpect(status().isForbidden());

        verify(challengeService, never()).updateChallenge(any(), any());
    }

    // ========== POST /challenges/{challengeId}/enroll/{userId} ==========

    @Test
    @WithMockUser(username = "user@test.com", roles = "USER")
    void enrollUser_shouldReturn201() throws Exception {
        UserChallengeResponse mockResponse = UserChallengeResponse.builder()
                .userId(99L)
                .challengeId(5L)
                .status(UserChallengeStatus.JOINED)
                .build();

        when(challengeService.enrollUser(5L, 99L)).thenReturn(mockResponse);

        mockMvc.perform(post("/challenges/5/enroll/99"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.userId").value(99))
                .andExpect(jsonPath("$.challengeId").value(5))
                .andExpect(jsonPath("$.status").value("JOINED"));

        verify(challengeService).enrollUser(5L, 99L);
    }

    // ========== GET /challenges/{challengeId}/user ==========

    @Test
    @WithMockUser(username = "user@test.com", roles = "USER")
    void getUserRankInChallenge_shouldReturnRankWhenAssigned() throws Exception {
        UserChallengeRankResponse mockResponse = UserChallengeRankResponse.builder()
                .userId(99L)
                .challengeId(10L)
                .status("RANKED")
                .finalScore(8500.0)
                .rank(3)
                .pointsAwarded(150)
                .joinedAt(startTime)
                .rankedAt(endTime)
                .build();

        when(challengeService.getUserRankInChallenge(10L, "user@test.com"))
                .thenReturn(mockResponse);

        mockMvc.perform(get("/challenges/10/user"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.userId").value(99))
                .andExpect(jsonPath("$.challengeId").value(10))
                .andExpect(jsonPath("$.status").value("RANKED"))
                .andExpect(jsonPath("$.rank").value(3))
                .andExpect(jsonPath("$.finalScore").value(8500.0))
                .andExpect(jsonPath("$.pointsAwarded").value(150));

        verify(challengeService).getUserRankInChallenge(10L, "user@test.com");
    }

    @Test
    @WithMockUser(username = "user@test.com", roles = "USER")
    void getUserRankInChallenge_shouldReturn200WhenRankIsNull() throws Exception {
        UserChallengeRankResponse mockResponse = UserChallengeRankResponse.builder()
                .userId(99L)
                .challengeId(10L)
                .status("JOINED")
                .finalScore(null)
                .rank(null)
                .pointsAwarded(0)
                .joinedAt(startTime)
                .rankedAt(null)
                .build();

        when(challengeService.getUserRankInChallenge(10L, "user@test.com"))
                .thenReturn(mockResponse);

        mockMvc.perform(get("/challenges/10/user"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status").value("JOINED"))
                .andExpect(jsonPath("$.rank").doesNotExist())
                .andExpect(jsonPath("$.rankedAt").doesNotExist());

        verify(challengeService).getUserRankInChallenge(10L, "user@test.com");
    }
}
