import { Activity, ArrowRight, Watch } from 'lucide-react'
import { FormEvent, useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ApiError, api } from '../api'
import { useAuth } from '../auth'
import type { Device } from '../types'

function AuthLayout({ children, title, caption }: { children: React.ReactNode; title: string; caption: string }) { return <div className="auth-page"><section className="auth-hero"><div className="brand"><Activity /> Pulse<span>Track</span></div><div><Watch size={54} /><h1>Every movement<br />counts.</h1><p>Connect your smartwatch, achieve your goals, and climb the leaderboard.</p></div></section><section className="auth-form"><div><h2>{title}</h2><p>{caption}</p>{children}</div></section></div> }
export function LoginPage() { const { login } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); setBusy(true); setError(''); try { await login(String(data.get('email')), String(data.get('password'))); navigate('/dashboard') } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to sign in.') } finally { setBusy(false) } }
  return <AuthLayout title="Welcome back" caption="Sign in to see how you’re progressing."><form onSubmit={submit}><label>Email<input name="email" type="email" required autoComplete="email" placeholder="you@example.com" /></label><label>Password<input name="password" type="password" required autoComplete="current-password" placeholder="Your password" /></label>{error && <p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Signing in…' : <>Sign in <ArrowRight size={18} /></>}</button></form><p className="auth-switch">New to PulseTrack? <Link to="/register">Create an account</Link></p></AuthLayout> }
export function RegisterPage() { const { register } = useAuth(); const navigate = useNavigate(); const [devices, setDevices] = useState<Device[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { api<Device[]>('/devices').then(setDevices).catch(() => setDevices([])) }, [])
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); setBusy(true); setError(''); try { await register({ email: String(data.get('email')), password: String(data.get('password')), fullName: String(data.get('fullName')), phone: String(data.get('phone')), deviceId: Number(data.get('deviceId')) }); navigate('/dashboard') } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to create your account.') } finally { setBusy(false) } }
  return <AuthLayout title="Create your account" caption="Start tracking your journey today."><form onSubmit={submit}><label>Full name<input name="fullName" required placeholder="Your name" /></label><label>Email<input name="email" type="email" required placeholder="you@example.com" /></label><label>Phone<input name="phone" required placeholder="+91 00000 00000" /></label><label>Device<select name="deviceId" required defaultValue=""><option value="" disabled>Select your smartwatch</option>{devices.map(device => <option value={device.id} key={device.id}>{device.deviceName} - {device.manufacturer} {device.model}</option>)}</select></label><label>Password<input name="password" type="password" minLength={8} required placeholder="At least 8 characters" /></label>{error && <p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Creating account...' : <>Create account <ArrowRight size={18} /></>}</button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></AuthLayout> }
