import { useEffect, useState } from 'react'
import { Activity, ChevronRight, CircleCheck, Dumbbell, Trophy } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../api'
import { EmptyState } from '../components/Layout'
import type { Challenge, Task } from '../types'

export function DashboardPage() { const [challenges, setChallenges] = useState<Challenge[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { Promise.all([api<Challenge[]>('/challenges'), api<Task[]>('/tasks')]).then(([c, t]) => { setChallenges(c); setTasks(t) }).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [])
  if (loading) return <div className="loading">Loading your fitness world…</div>
  if (error) return <div className="notice error">{error}</div>
  return <><section className="welcome"><div><p className="eyebrow">YOUR FITNESS HUB</p><h1>Make today count.</h1><p>Take on challenges, finish tasks, and earn your place at the top.</p></div><div className="watch-orb"><Activity size={58} /></div></section><section className="stats"><div><Trophy /><p>Active challenges</p><strong>{challenges.length}</strong></div><div><Dumbbell /><p>Available tasks</p><strong>{tasks.length}</strong></div><div><CircleCheck /><p>Ready to achieve</p><strong>{tasks.filter(task => task.status === 'ACTIVE').length}</strong></div></section><section id="challenges" className="section-heading"><div><p className="eyebrow">COMPETE &amp; GROW</p><h2>Active challenges</h2></div></section>{challenges.length ? <div className="challenge-grid">{challenges.map(challenge => <Link className="challenge-card" to={`/challenges/${challenge.id}`} key={challenge.id}><span className="status">{challenge.status}</span><h3>{challenge.name}</h3><p>{challenge.description || 'A new opportunity to move, improve, and compete.'}</p><footer><span>{challenge.tasks?.length ?? 0} tasks</span><span>View challenge <ChevronRight size={16} /></span></footer></Link>)}</div> : <EmptyState message="No challenges are available yet. Check back soon." />}<section className="section-heading"><div><p className="eyebrow">BUILD MOMENTUM</p><h2>Tasks to complete</h2></div></section>{tasks.length ? <div className="task-list">{tasks.slice(0, 5).map(task => <article key={task.id}><div className="task-icon"><Dumbbell size={20} /></div><div><h3>{task.name}</h3><p>{task.description || `${task.requiredMetric} target: ${task.targetValue}`}</p></div><strong>+{task.rewardPoints} pts</strong></article>)}</div> : <EmptyState message="No tasks are available right now." />}</> }
